markdown: rdiscount
permalink: /:year/:month/:title/
url: http://lufo.me
pygments: true
permalink: /:year/:month/:day/:title.html
name: "lufo"

author: "lufo"
atom-baseurl: "http://lufo816.github.com"