markdown: redcarpet
pygments: true
permalink: /:year/:month/:day/:title.html
name: "lufo"

author: "lufo"
atom-baseurl: "http://lufo816.github.com"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Shihuo
    class: fa fa-comment-o
    href: /shihuo.html
  - title: ToBuy
    class: fa fa-shopping-cart
    href: /to_buy_list.html
  - title: Blogroll
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

